version: '3.1'

services:

  wordpress:
    image: wordpress:5.0.3
    environment:
      - WORDPRESS_DB_PASSWORD=wordpress
    ports:
      - 13080:80
    volumes:
      - ./env/dev/wp-config.php:/usr/src/wordpress/wp-config-sample.php
      - ./theme:/var/www/html/wp-content/themes/theme:rw
      - ./plugin:/var/www/html/wp-content/plugins/plugin:rw
      - ./public/wp-content:/var/www/html/wp-content:rw
      - ./vendor:/var/www/vendor:rw
    restart: "no"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    volumes:
      - ./volumes/mysql/:/var/lib/mysql
    restart: "no"

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
    ports:
      - 13081:8080
    restart: "no"